**Simple Implementation of RNN using numpy**

state_t = 0

for input_t in input_sequence 

    output_t = activation(dot(W, input_t) + dot(U, state_t) + b)
    state_t = output_t

In [1]:
import numpy as np

In [2]:
#Number of timesteps in the input sequence
timesteps = 100

#Dimensionality of the input feature space
input_features = 32

#Dimensionality of the output feature space
output_features = 64

In [3]:
#input data: random noise(as example)
inputs = np.random.random((timesteps, input_features))

In [4]:
inputs

array([[0.1058018 , 0.60738741, 0.08692739, ..., 0.49356146, 0.47365327,
        0.95716898],
       [0.32418164, 0.84532453, 0.90400331, ..., 0.26408832, 0.20824918,
        0.7855205 ],
       [0.9646335 , 0.17333089, 0.91072719, ..., 0.68402479, 0.22245209,
        0.73458887],
       ...,
       [0.50301196, 0.80682079, 0.5336578 , ..., 0.81193641, 0.40927736,
        0.30852679],
       [0.5882097 , 0.92912539, 0.45626842, ..., 0.06458964, 0.96412385,
        0.86670253],
       [0.13108844, 0.05376509, 0.04597246, ..., 0.38824836, 0.68228762,
        0.3829557 ]])

In [5]:
#initial state: an all zero vector
state_t = np.zeros((output_features,))

In [6]:
#Create random weights matrices
W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features,))

In [7]:
np.shape(W)

(64, 32)

In [8]:
np.shape(b)

(64,)

In [9]:
successive_outputs = []

In [11]:
#input_t is a vector of shape (input_features,).
for input_t in inputs:
    
    #Combines the input with the current state (the previous output) to obtain the current output
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    
    #Stores this output in a list
    successive_outputs.append(output_t)
    
    #Updates the state of the network for the next timestep
    state_t = output_t

In [12]:
#The final output is a 2D tensor of shape (timesteps, output_features).
final_output_sequence = np.concatenate(successive_outputs, axis = 0)

In [13]:
np.shape(final_output_sequence)

(6400,)

In [15]:
len(final_output_sequence)

6400

In [16]:
final_output_sequence

array([0.99999999, 0.99999999, 0.9999996 , ..., 1.        , 1.        ,
       1.        ])

In [17]:
#last output_t
output_t

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])