<a href="https://colab.research.google.com/github/dimasarinugroho/Deep-Learning-With-Python/blob/master/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama: Dimas Ari Nugroho


Status: Freelance / S1 Matematika ITS

Spesialisasi : Data Science dan Data Analyst


Topik pembahasan : mengimplementasikan tensor pada python untuk multi-dimensional array

**1. Data Representation**

**Tensors**


*   Tensor merupakan wadah bagi suatu data
*   Matriks --> Tensor 2D
*   Tensor merupakan generalisasi pada matriks untuk angka yang berubah-ubah pada suatu dimensi
*   Dimensi yang dimaksud pada terminologi tensor merupakan Axis / Grafik



**Scalars**



*   Tensor yang memuat hanya satu angka --> skalar(i.e 0 dim atau 0D tensor)
*   float32 atau float64 (untuk numpy) --> tensor skalar(array skalar)
*   menggunakan 'ndim' --> menampilkan jumlah axes / grafik
*   tensor skalar memiliki 0 axes / grafik (ndim=0)
*   Rank --> jumlah axes / grafik pada tensor



In [1]:
#import numpy
import numpy as np

In [2]:
x = np.array(104)

In [3]:
x

array(104)

In [4]:
x.ndim

0

**2. Vectors**



*   Angka pada suatu array --> Vektor / 1D tensors
*   1D tensors hanya mempunyai 1 axes / grafik



In [5]:
x = np.array([12, 34, 68, 104, 5])

In [6]:
x

array([ 12,  34,  68, 104,   5])

In [7]:
x.ndim

1

In [8]:
print("type is: ", type(x))
print("dtype is: ", x.dtype)

type is:  <class 'numpy.ndarray'>
dtype is:  int64


**3. Tentang Vektor**
*   Vektor 5-dimensi
*   Vektor 5-dimensi vs Tensor 5-dimensi
    *   Vektor 5-dimensi hanya mempunyai 1 sumbu dan memiliki 5 dimensi sepanjang sumbu
    *   Tensor 5-dimensi hanya mempunyai 1 sumbu dan memiliki 5 dimensi sepanjang sumbu

    **Membingungkan!!**
    *   Dimensi dapat menunjukkan jumlah entri di sepanjang sumbu tertentu (pada kasus Vektor 5-dimensi)
    *   Jumlah sumbu pada tensor (sebagai contoh Tensor 5-dimensi)

    **Penggunaan *Rank*** 
    *   *Rank* --> Jumlah sumbu pada tensor
    *   Jadi gunakan --> Tensor peringkat 5    







**Matriks**
*   Vektor pada suatu *array* dikatakan matriks, atau 2D tensor
*   Matiks memiliki dua sumbu, baris dan kolom



In [9]:
x=np.array([[51, 70, 2, 32, 3], 
           [69, 7, 3, 35, 10], 
           [1, 8, 4, 6, 9]])

In [10]:
x

array([[51, 70,  2, 32,  3],
       [69,  7,  3, 35, 10],
       [ 1,  8,  4,  6,  9]])

In [11]:
x.ndim

2

**Vektor 3-Dimensi**

In [12]:
x = np.array([
         [[51, 70, 2, 32, 3], 
           [69, 7, 3, 35, 10], 
           [1, 8, 4, 6, 9]],

           [[51, 70, 2, 32, 3], 
           [69, 7, 3, 35, 10], 
           [1, 8, 4, 6, 9]],

           [[51, 70, 2, 32, 3], 
           [69, 7, 3, 35, 10], 
           [1, 8, 4, 6, 9]]     
])

In [13]:
x

array([[[51, 70,  2, 32,  3],
        [69,  7,  3, 35, 10],
        [ 1,  8,  4,  6,  9]],

       [[51, 70,  2, 32,  3],
        [69,  7,  3, 35, 10],
        [ 1,  8,  4,  6,  9]],

       [[51, 70,  2, 32,  3],
        [69,  7,  3, 35, 10],
        [ 1,  8,  4,  6,  9]]])

In [14]:
x.ndim

3

In [15]:
print("type is: ", type(x))
print("dtype is: ", x.dtype)

type is:  <class 'numpy.ndarray'>
dtype is:  int64


**Operasi pada Tensor**

*   Element-Wise operations
*   Addition or different shaped tensors
*   dot product
*   reshaping

**Element-Wise operations**

*   Add, Subtraction etc



In [16]:
def my_add(x, y):
  assert len(x.shape)==2
  assert x.shape == y.shape     # x, y ---> 2D numpy tensors

  x = x.copy()      # avoida overwriting the input sensors

  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      x[i, j] = x[i, j] + y[i, j]
  return x

In [17]:
x=np.array([[5.2, 2, 78, 2, 34], 
           [6, 79, 3, 35, 1], 
           [7, 80, 4, 36, 2]])

In [18]:
x.ndim

2

In [19]:
x.shape[0]


3

In [20]:
x.shape[1]

5

In [21]:
r = x.shape

In [22]:
print(r[0], r[1])

3 5


In [23]:
y = np.array([[4,2,1,3,0],
               [6,1,3,5,2],
              [7,8,4,6,2]])

In [24]:
y.ndim

2

In [25]:
z = my_add(x, y)

In [26]:
z

array([[ 9.2,  4. , 79. ,  5. , 34. ],
       [12. , 80. ,  6. , 40. ,  3. ],
       [14. , 88. ,  8. , 42. ,  4. ]])

**Using Numpy Array**

In [27]:
# Add operations using numpy

z = x + y

In [28]:
z

array([[ 9.2,  4. , 79. ,  5. , 34. ],
       [12. , 80. ,  6. , 40. ,  3. ],
       [14. , 88. ,  8. , 42. ,  4. ]])

In [29]:
# set elements less than a particular value to max
z = np.maximum(y, 5.)

In [30]:
z

array([[5., 5., 5., 5., 5.],
       [6., 5., 5., 5., 5.],
       [7., 8., 5., 6., 5.]])

**Adding dissimilar tensors**

In [31]:
def my_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = x[i, j] + y[j]
  return x

In [32]:
x=np.array([[5.2, 2, 78, 2, 34], 
           [6, 79, 3, 35, 1], 
           [7, 80, 4, 36, 2]])

In [33]:
x.ndim    # len(x.shape)

2

In [34]:
y=np.array([1, 2, 3, 1, 2])

In [35]:
y.ndim  # len(y.shape)

1

In [36]:
z = my_add_matrix_and_vector(x,y)

In [37]:
z

array([[ 6.2,  4. , 81. ,  3. , 36. ],
       [ 7. , 81. ,  6. , 36. ,  3. ],
       [ 8. , 82. ,  7. , 37. ,  4. ]])

In [38]:
a = np.random.random((1, 2, 3, 10))

In [39]:
a.ndim

4

In [40]:
a

array([[[[0.81289423, 0.34490283, 0.22553859, 0.0906605 , 0.62210018,
          0.79581232, 0.71866624, 0.3790127 , 0.1765873 , 0.42575715],
         [0.60934901, 0.88159582, 0.73035199, 0.07253202, 0.50642523,
          0.85550255, 0.90487954, 0.16179967, 0.86871598, 0.74876808],
         [0.68609735, 0.44498136, 0.93922147, 0.91873403, 0.21096576,
          0.84580862, 0.51942039, 0.75521665, 0.56453815, 0.99851924]],

        [[0.63986026, 0.1812244 , 0.7168835 , 0.43589033, 0.23953237,
          0.29833066, 0.70755032, 0.70641521, 0.37900149, 0.58894889],
         [0.4412931 , 0.37038816, 0.91905938, 0.56346506, 0.00250187,
          0.2547697 , 0.75981707, 0.78913231, 0.15889401, 0.92121309],
         [0.08209148, 0.26751344, 0.32981685, 0.7487602 , 0.06462906,
          0.51841315, 0.31375828, 0.22097017, 0.7525236 , 0.63395055]]]])

In [41]:
b = np.random.random((3, 10))

In [42]:
b.ndim

2

In [43]:
b

array([[0.31686594, 0.52880077, 0.26364508, 0.36373623, 0.24231241,
        0.28740037, 0.14855233, 0.79106772, 0.33606578, 0.37854366],
       [0.71667887, 0.61917797, 0.53258471, 0.5674172 , 0.2901436 ,
        0.04382906, 0.99475237, 0.23479833, 0.23664987, 0.12583592],
       [0.93000709, 0.32500351, 0.03914433, 0.98911518, 0.18403594,
        0.94802692, 0.53050875, 0.65510235, 0.0845398 , 0.95772211]])

In [44]:
c = np.maximum(a, b)

In [45]:
c

array([[[[0.81289423, 0.52880077, 0.26364508, 0.36373623, 0.62210018,
          0.79581232, 0.71866624, 0.79106772, 0.33606578, 0.42575715],
         [0.71667887, 0.88159582, 0.73035199, 0.5674172 , 0.50642523,
          0.85550255, 0.99475237, 0.23479833, 0.86871598, 0.74876808],
         [0.93000709, 0.44498136, 0.93922147, 0.98911518, 0.21096576,
          0.94802692, 0.53050875, 0.75521665, 0.56453815, 0.99851924]],

        [[0.63986026, 0.52880077, 0.7168835 , 0.43589033, 0.24231241,
          0.29833066, 0.70755032, 0.79106772, 0.37900149, 0.58894889],
         [0.71667887, 0.61917797, 0.91905938, 0.5674172 , 0.2901436 ,
          0.2547697 , 0.99475237, 0.78913231, 0.23664987, 0.92121309],
         [0.93000709, 0.32500351, 0.32981685, 0.98911518, 0.18403594,
          0.94802692, 0.53050875, 0.65510235, 0.7525236 , 0.95772211]]]])

**Dot Product**

In [46]:
def my_vector_dot(x,y):
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]

  z = 0
  for i in range (x.shape[0]):
    z = z + x[i]*y[i]
  return z

In [47]:
a = np.array([5, 2, 3, 4, 6])

In [48]:
b = np.array([3, 2, 4, 1, 5])

In [49]:
c = my_vector_dot(a, b)

In [50]:
c

65

In [51]:
c = np.dot(a, b)

In [52]:
c

65

In [53]:
def my_matrix_vector_dot(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] = z[i] + x[i,j] * y[j]
  return z

In [54]:
a = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]
])

In [55]:
b = np.array([3, 2, 4, 1, 5])

In [56]:
c = my_matrix_vector_dot(a,b)

In [57]:
c

array([213., 228., 243.])

In [58]:
def my_matrix_dot(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]

  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range (x.shape[0]):
    for j in range (y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = my_vector_dot(row_x, column_y)
  return z

In [59]:
a = np.array([[5, 7, 2, 34, 0],
              [6, 7, 3, 35, 1],
              [7, 8, 4, 36, 2]
])

In [60]:
b = np.array([
              [4, 2, 1],
              [6, 1, 3],
              [7, 8, 4],
              [3, 4, 5],
              [2, 2, 2]
])

In [61]:
c = my_matrix_dot(a,b)

In [62]:
c

array([[178., 169., 204.],
       [194., 185., 216.],
       [216., 202., 231.]])

**Reshaping**

In [63]:
x = np.array([[0.2, 1.1],
              [2.4, 3.5],
              [4.1, 5.3]
])

In [64]:
x

array([[0.2, 1.1],
       [2.4, 3.5],
       [4.1, 5.3]])

In [65]:
x.shape

(3, 2)

In [66]:
# reshape

x = x.reshape((6, 1))

In [67]:
x.shape

(6, 1)

In [68]:
x

array([[0.2],
       [1.1],
       [2.4],
       [3.5],
       [4.1],
       [5.3]])

In [69]:
x = x.reshape((2,3))

In [70]:
x.shape

(2, 3)

In [71]:
x

array([[0.2, 1.1, 2.4],
       [3.5, 4.1, 5.3]])

**Transpose**

In [72]:
# Transpose

x = np.zeros((300, 20)) # membuat matriks nol

In [73]:
x.shape

(300, 20)

In [74]:
# Ditransposkan

y = np.transpose(x)

In [75]:
y.shape

(20, 300)